name: Continuous ML Pipeline

on:
    push:
        branches:
            - main

jobs: 
    build:
        runs-on: ubuntu-latest
        # container: docker://...
        defaults:
            run:
                working-directory: ./E2EPROJECT/  # Updated working directory
              shell: bash -1 {0}
        # env:
        #     MODE: ".env"
        steps:
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt  

            - name: Run data ingestion
              run: python src/components/data_ingestion.py  

            # Uncomment and modify the following steps based on your pipeline requirements
            # - name: Run data transformation
            #   run: python components/data_transformation.py

            # - name: Run model training
            #   run: python components/model_trainer.py

            - name: Commit the results
              run: |
                git config --global user.name "Timon Kazman"
                git config --global user.email "timonkazman@yahoo.de"
                git add .
                git commit -m "Add results"

# Add more jobs and steps as needed for other stages of your ML pipeline.
